document.writeln("	<!--footer start-->");
document.writeln("	<div class=\'footer\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<div class=\'bottom_nav col-md-12\'>");
document.writeln("				<div class=\'col-md-3 box_1\'>");
document.writeln("					<a href=\'index.html\'><img src=\'images/head foot/logob.png\' alt=\'科旺达logo\'></a>");
document.writeln("					<p>北京科旺达信息技术有限公司是专注为企业提供软件技术开发，帮助企业提高核心竞争力和降低软件项目成本。</p>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-2 box_2\'>");
document.writeln("					<h5>平台目录</h5>");
document.writeln("					<ul class=\'footer_list\'>");
document.writeln("						<li><a href=\'index.html\'>首页</a></li>");
document.writeln("						<li><a href=\'product.html\'>产品中心</a></li>");
document.writeln("						<li><a href=\'case.html\'>客户案例</a></li>");
document.writeln("						<li><a href=\'solution.html\'>解决方案</a></li>");
document.writeln("						<li><a href=\'news.html\'>新闻专栏</a></li>");
document.writeln("						<li><a href=\'aptitude.html\'>企业资质</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-2 box_3\'>");
document.writeln("					<h5>服务支持</h5>");
document.writeln("					<ul class=\'footer_list\'>");
document.writeln("						<li><a href=\'problem.html\'>常见问题</a></li>");
document.writeln("						<li><a href=\'solution.html\'>解决方案</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-2 box_4\'>");
document.writeln("					<h5>相关平台</h5>");
document.writeln("					<ul class=\'footer_list\'>");
document.writeln("						<li><a href=\'#\' data-toggle=\'modal\' data-target=\'#myModal\'>微信公众号</a></li>");
document.writeln("						<!-- Modal -->");
document.writeln("						<div class=\'modal fade\' id=\'myModal\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\'>");
document.writeln("							<div class=\'modal-dialog\' role=\'document\'>");
document.writeln("							<div class=\'modal-content\'>");
document.writeln("								<div class=\'modal-header\'>");
document.writeln("								<button type=\'button\' class=\'close\' data-dismiss=\'modal\' aria-label=\'Close\'><span aria-hidden=\'true\'>&times;</span></button>");
document.writeln("								<h4 class=\'modal-title\' id=\'myModalLabel\'>微信公众号</h4>");
document.writeln("								</div>");
document.writeln("								<div class=\'modal-body\'>");
document.writeln("								<img src=\'images/head foot/wxgzh.jpg\' alt=\'微信公众号\' style=\'text-align: center;margin: 0 auto;display: block;\'>");
document.writeln("								<p style=\'color: #333;text-align: center;\'>扫码关注官方指定微信公众号</p>");
document.writeln("								<p style=\'color: #333;text-align: center;\'>或微信搜索“<span style=\'color: #1153a9\'>科旺达官网</span>”公众号</p>");
document.writeln("								</div>");
document.writeln("								<div class=\'modal-footer\'>");
document.writeln("								<button type=\'button\' class=\'btn btn-default\' data-dismiss=\'modal\'>关闭弹框</button>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<li><a href=\'#\' data-toggle=\'modal\' data-target=\'#myModal1\'>支付宝生活号</a></li>");
document.writeln("						<!-- Modal -->");
document.writeln("						<div class=\'modal fade\' id=\'myModal1\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\'>");
document.writeln("							<div class=\'modal-dialog\' role=\'document\'>");
document.writeln("							<div class=\'modal-content\'>");
document.writeln("								<div class=\'modal-header\'>");
document.writeln("								<button type=\'button\' class=\'close\' data-dismiss=\'modal\' aria-label=\'Close\'><span aria-hidden=\'true\'>&times;</span></button>");
document.writeln("								<h4 class=\'modal-title\' id=\'myModalLabel\'>支付宝生活号</h4>");
document.writeln("								</div>");
document.writeln("								<div class=\'modal-body\'>");
document.writeln("								<img src=\'images/head foot/zfbshh.jpg\' alt=\'支付宝生活号\' style=\'text-align: center;margin: 0 auto;display: block;\'>");
document.writeln("								<p style=\'color: #333;text-align: center;\'>扫码关注官方指定支付宝生活号</p>");
document.writeln("								<p style=\'color: #333;text-align: center;\'>或支付宝搜索“<span style=\'color: #1153a9\'>北京科旺达</span>”生活号</p>");
document.writeln("								</div>");
document.writeln("								<div class=\'modal-footer\'>");
document.writeln("								<button type=\'button\' class=\'btn btn-default\' data-dismiss=\'modal\'>关闭弹框</button>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<li><a href=\'#\' data-toggle=\'modal\' data-target=\'#myModal2\'>支付宝小程序</a></li>");
document.writeln("						<!-- Modal -->");
document.writeln("						<div class=\'modal fade\' id=\'myModal2\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\'>");
document.writeln("							<div class=\'modal-dialog\' role=\'document\'>");
document.writeln("							<div class=\'modal-content\'>");
document.writeln("								<div class=\'modal-header\'>");
document.writeln("								<button type=\'button\' class=\'close\' data-dismiss=\'modal\' aria-label=\'Close\'><span aria-hidden=\'true\'>&times;</span></button>");
document.writeln("								<h4 class=\'modal-title\' id=\'myModalLabel\'>支付宝小程序</h4>");
document.writeln("								</div>");
document.writeln("								<div class=\'modal-body\'>");
document.writeln("								<img src=\'images/head foot/zfbshh.jpg\' alt=\'支付宝生活号\' style=\'text-align: center;margin: 0 auto;display: block;\'>");
document.writeln("								<p style=\'color: #333;text-align: center;\'>扫码关注官方指定支付宝小程序</p>");
document.writeln("								<p style=\'color: #333;text-align: center;\'>或支付宝搜索“<span style=\'color: #1153a9\'>科旺达软件服务</span>”小程序</p>");
document.writeln("								</div>");
document.writeln("								<div class=\'modal-footer\'>");
document.writeln("								<button type=\'button\' class=\'btn btn-default\' data-dismiss=\'modal\'>关闭弹框</button>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("							</div>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-3 box_5\'>");
document.writeln("					<h5>联系详情</h5>");
document.writeln("					<ul class=\'footer_list\'>");
document.writeln("						<li>180-0135-6892</li>");
document.writeln("						<li>kwd@kwangda.com</li>");
document.writeln("						<li>中关村大街1号11层1121-187</li>");
document.writeln("						<li>周一至周五  08:00~~18:00</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div class=\'copyright col-xs-12 col-md-12\'>");
document.writeln("				<p>© 2018 KWANGDA.COM <a href=\'https://www.kwangda.com\'>北京科旺达&nbsp;&nbsp;</a><a href=\'http://www.miitbeian.gov.cn/\'>京ICP备18032811号 &nbsp;&nbsp;</a><a target=\'_blank\' href=\'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802026750\'><img src=\'images/head foot/ghs.png\' alt=\'beian\'> 京公网安备 11010802026750号</p></a></p>");
document.writeln("			</div>");
document.writeln("			<div class=\'ICP col-md-12\'>");
document.writeln("				<a id=\'_pingansec_bottomimagesmall_shiming\' href=\'http://si.trustutn.org/info?sn=290180719036002012821&amp;certType=1\'><img src=\'images/head foot/renzheng1.png\' alt=\'行业示范\'></a>");
document.writeln("				<a id=\'_pingansec_bottomimagesmall_shiming\' href=\'http://si.trustutn.org/info?sn=290180719036002012821&amp;certType=1\'><img src=\'images/head foot/shiming.png\' alt=\'实名网站\'></a>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");